---
- name: Ensure .fonts directory exists
  file:
    path: ~/.fonts
    state: directory
  become: no

- name: Clone firacode repository
  git:
    repo: https://github.com/tonsky/FiraCode.git
    dest: ~/.fonts/FiraCode
  become: no

- name: Clone fire repository
  git:
    repo: https://github.com/mozilla/Fira.git
    dest: ~/.fonts/Fira
  become: no


