---
- name: Ensure git installation
  apt:
    name: git
    state: present
  become: yes

- name: git email global config
  shell: git config --global user.email "RFmind@gmail.com"
  become: no

- name: git user global config
  shell: git config --global user.name "Ruslan Filimonov"
  become: no

