---
- name: Ensure Installation of i3
  apt:
    name: "i3"
    state: present
  become: yes

- name: Ensure .config/i3 directory exists
  file:
    path: ~/.config/i3
    state: directory
  become: no

- name: Ensure .config/i3status directory exists
  file:
    path: ~/.config/i3status
    state: directory
  become: no

- name: Clone i3 config
  git:
    repo: https://github.com/rfmind/i3config.git
    dest: ~/Code/i3config
  become: no

- name: Copy i3 config file
  copy:
    src: ~/Code/i3config/i3/config
    dest: ~/.config/i3/config
  become: no

- name: Copy i3status config file
  copy:
    src: ~/Code/i3config/i3status/config
    dest: ~/.config/i3status/config
  become: no
