---
- name: Download rustup script
  get_url:
      url: https://sh.rustup.rs
      dest: ~/Code/install-rust
      validate_certs: no
  become: no

- name: Install latest stable rust
  command: sh ~/Code/install-rust -y
  become: no

