---
- name: Ensure sublime dependencies are installed
  apt:
    name: "{{ sublime_dependencies }}"
    state: present
  become: yes

- name: Add GPG key for sublime
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes

- name: Add apt repository for sublime
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
  become: yes  

- name: Ensure sublime installation
  apt:
    name: sublime-text
    state: present
    update_cache: yes
  become: yes
